import sqlite3 as base

# create or connect a data base
data_base = base.connect("demo1.db")

# create a cursor
cursor = data_base.cursor()
cursor.execute('''create table IF NOT EXISTS CUSTOMER(
CUST_ID INT PRIMARY KEY,
PASSWORD VARCHAR(20),
NAME VARCHAR(50),
DOB DATE,
AGE INT,
GENDER VARCHAR(6),
EMAIL VARCHAR(50),
CONTACT INT,
PAN INT,
NATIONALITY VARCHAR(15)
);''')
cursor.execute('''create table IF NOT EXISTS CUSTOMER_Address(
CUST_ID INT PRIMARY KEY,
STREET VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
PIN INT,
Foreign Key(CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE
);''')
cursor.execute('''CREATE TABLE IF NOT EXISTS INTEREST(
INTEREST_ID INT PRIMARY KEY,
SAVING_INT FLOAT
);''')


cursor.execute('''CREATE TABLE IF NOT EXISTS ACCOUNT(
AC_NO INT PRIMARY KEY,
INTEREST_ID INT,
CUST_ID INT,
AC_TYPE VARCHAR(10),
BALANCE INT, 
INTEREST_AMOUNT INT,
INTEREST_RATE INT,
OPEN_DATE DATE,
Foreign Key(CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE,
Foreign Key(INTEREST_ID) REFERENCES INTEREST(INTEREST_ID) ON DELETE CASCADE
);''')

cursor.execute('''CREATE TABLE IF NOT EXISTS BRANCH(
BRANCH_ID INT PRIMARY KEY,
BRANCH_NAME VARCHAR(50)
);''')
cursor.execute('''CREATE TABLE IF NOT EXISTS BRANCH_ADDRESS(
BRANCH_ID INT PRIMARY KEY,
STATE VARCHAR(20),
COUNTRY VARCHAR(20),
PIN INT,
Foreign Key(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE
);''')

cursor.execute('''CREATE TABLE IF NOT EXISTS OFFICER(
EMP_ID INT PRIMARY KEY,
BRANCH_ID INT,
NAME VARCHAR(50),
EMAIL VARCHAR(50),
GENDER VARCHAR(6),
CONTACT INT,
NATIONALITY VARCHAR(20),
DOB DATE,
USERNAME VARCHAR(20),
PASSWORD VARCHAR(20),
Foreign Key(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE
);''')
cursor.execute('''CREATE TABLE IF NOT EXISTS OFFICER_ADDRESS(
EMP_ID INT PRIMARY KEY,
STREET VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
PIN INT,
Foreign Key(EMP_ID) REFERENCES OFFICER(EMP_ID) ON DELETE CASCADE
);''')

cursor.execute('''CREATE TABLE IF NOT EXISTS MANAGER(
EMP_ID INT PRIMARY KEY,
BRANCH_ID INT ,
NAME VARCHAR(50),
EMAIL VARCHAR(50),
GENDER VARCHAR(6),
CONTACT INT,
NATIONALITY VARCHAR(20),
DOB DATE,
USERNAME VARCHAR(20),
PASSWORD VARCHAR(20),
Foreign Key(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE
);''')

cursor.execute('''CREATE TABLE IF NOT EXISTS MANAGER_ADDRESS(
EMP_ID INT PRIMARY KEY,
STREET VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
PIN INT,
Foreign Key(EMP_ID) REFERENCES OFFICER(EMP_ID) ON DELETE CASCADE
);''')
cursor.execute('''CREATE TABLE IF NOT EXISTS TRANSACTIONS(
AC_NO INT ,
TRANS_ID INT PRIMARY KEY,
TRANS_TYPE VARCHAR(20),
DATE_OF_TRANS DATE,
Foreign Key(AC_NO) REFERENCES ACCOUNT(AC_NO) ON DELETE CASCADE);
''')







cursor.execute("SELECT *, oid FROM CUSTOMER")
cursor.execute("SELECT *, oid FROM CUSTOMER_Address")
cursor.execute("SELECT *, oid FROM INTEREST")
cursor.execute("SELECT *, oid FROM ACCOUNT")
cursor.execute("SELECT *, oid FROM BRANCH")
cursor.execute("SELECT *, oid FROM OFFICER")
cursor.execute("SELECT *, oid FROM BRANCH_ADDRESS")
cursor.execute("SELECT *, oid FROM OFFICER_ADDRESS")
cursor.execute("SELECT *, oid FROM MANAGER")
cursor.execute("SELECT *, oid FROM MANAGER_ADDRESS")
cursor.execute("SELECT *, oid FROM TRANSACTIONS")


#cursor.execute("DELETE from users WHERE oid='0'")
print(cursor.fetchall())


# commit all the changes
data_base.commit()

# close the database
data_base.close()