create table CUSTOMER(
CUST_ID INT PRIMARY KEY,
PASSWORD VARCHAR(20),
NAME VARCHAR(50),
DOB DATE,
AGE INT,
GENDER VARCHAR(6),
EMAIL VARCHAR(50),
CONTACT INT,
PAN INT,
NATIONALITY VARCHAR(15)
);

create table CUSTOMER_Address(
CUST_ID INT PRIMARY KEY,
STREET VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
PIN INT,
Foreign Key(CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE
);

CREATE TABLE INTEREST(
INTEREST_ID INT PRIMARY KEY,
SAVING_INT FLOAT
);


CREATE TABLE ACCOUNT(
AC_NO INT PRIMARY KEY,
CUST_ID INT PRIMARY KEY,
Foreign Key(CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE,
AC_TYPE VARCHAR(10),
BALANCE INT, 
Foreign Key(INTEREST_ID) REFERENCES INTEREST(INTEREST_ID) ON DELETE CASCADE,
INTEREST_AMOUNT INT,
INTEREST_RATE INT,
OPEN_DATE DATE
);

CREATE TABLE BRANCH(
BRANCH_ID INT PRIMARY KEY,
BRANCH_NAME VARCHAR(50)
);
CREATE TABLE BRANCH_ADDRESS(
BRANCH_ID INT PRIMARY KEY,
Foreign Key(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE,
STATE VARCHAR(20),
COUNTRY VARCHAR(20),
PIN INT);

CREATE TABLE OFFICER(
EMP_ID INT PRIMARY KEY,
BRANCH_ID INT PRIMARY KEY,
Foreign Key(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE,
NAME VARCHAR(50),
EMAIL VARCHAR(50),
GENDER VARCHAR(6),
CONTACT INT,
NATIONALITY VARCHAR(20),
DOB DATE,
USERNAME VARCHAR(20),
PASSWORD VARCHAR(20)
);
CREATE TABLE OFFICER_ADDRESS(
EMP_ID INT PRIMARY KEY,
Foreign Key(EMP_ID) REFERENCES OFFICER(EMP_ID) ON DELETE CASCADE,
STREET VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
PIN INT
);

CREATE TABLE MANAGER(
EMP_ID INT PRIMARY KEY,
BRANCH_ID INT PRIMARY KEY,
Foreign Key(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) ON DELETE CASCADE,
NAME VARCHAR(50),
EMAIL VARCHAR(50),
GENDER VARCHAR(6),
CONTACT INT,
NATIONALITY VARCHAR(20),
DOB DATE,
USERNAME VARCHAR(20),
PASSWORD VARCHAR(20)
);
CREATE TABLE MANAGER_ADDRESS(
EMP_ID INT PRIMARY KEY,
Foreign Key(EMP_ID) REFERENCES OFFICER(EMP_ID) ON DELETE CASCADE,
STREET VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
PIN INT
);

CREATE TABLE TRANSACTION(
TRANS_ID INT PRIMARY KEY,
AC_NO INT PRIMARY KEY,
Foreign Key(AC_NO) REFERENCES ACCOUNT(AC_NO) ON DELETE CASCADE,
TRANS_TYPE VARCHAR(20),
DATE_OF_TRANS DATE);

